cloud1_manage_firewall: true
cloud1_project_dir: /opt/cloud-1

cloud1_tls_days: 3650
cloud1_tls_country: "FR"
cloud1_tls_state: "Ile-de-France"
cloud1_tls_locality: "Paris"
cloud1_tls_org: "42 Cloud-1"
cloud1_public_host: "54.37.228.55"
cloud1_domain: "{{ cloud1_public_host }}"
cloud1_pma_path: "/phpmyadmin"

cloud1_compose_project_name: "cloud1"

cloud1_db_name: "wordpress"
cloud1_db_user: "wordpress"
cloud1_wp_table_prefix: "wp_"

cloud1_image_nginx: "nginx:1-alpine"
cloud1_image_mariadb: "mariadb:11"
cloud1_image_wordpress: "wordpress:6-php8.3-fpm-alpine"
cloud1_image_phpmyadmin: "phpmyadmin:5-apache"
