---
- name: Configure firewall when enabled
  when: cloud1_manage_firewall | bool
  block:
    - name: Allow OpenSSH before enabling firewall
      ansible.builtin.command: ufw allow OpenSSH
      register: ufw_allow_ssh
      changed_when: "'Rule added' in ufw_allow_ssh.stdout"

    - name: Allow HTTP
      ansible.builtin.command: ufw allow 80/tcp
      register: ufw_allow_http
      changed_when: "'Rule added' in ufw_allow_http.stdout"

    - name: Allow HTTPS
      ansible.builtin.command: ufw allow 443/tcp
      register: ufw_allow_https
      changed_when: "'Rule added' in ufw_allow_https.stdout"

    - name: Enable UFW
      ansible.builtin.command: ufw --force enable
      register: ufw_enable
      changed_when: "'Firewall is active' in ufw_enable.stdout"
